version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - net

  db:
    build: db  
    ports:
      - "27017:27017"
    networks:
      - net

networks:
  net:
    driver: bridge
